$primary = rgb(86d2f1)
$surface = rgb(0e1416)
$secondary = rgb(a9cdde)
$error = rgb(ffaa97)
$tertiary = rgb(c6c4e9)
$surface_lowest = rgb(090f11)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
