color0 #121413
color1 #ffb4ab
color2 #afcdc7
color3 #bec9c6
color4 #c9c3de
color5 #afcdc7
color6 #bec9c6
color7 #e3e2e1
color8 #8b9290
color9 #ffb4ab
color10 #afcdc7
color11 #bec9c6
color12 #c9c3de
color13 #afcdc7
color14 #bec9c6
color15 #e3e2e1

cursor                #e3e2e1
cursor_text_color     #121413
background            #121413
foreground            #e3e2e1
selection_foreground  #c1c8c6
selection_background  #414847
active_border_color   #afcdc7
inactive_border_color #414847
url_color             #afcdc7

active_tab_foreground   #1a3531
active_tab_background   #afcdc7
inactive_tab_foreground #c1c8c6
inactive_tab_background #414847
cursor_trail_color      #c1c8c6
