color0 #0e1416
color1 #ffaa97
color2 #86d2f1
color3 #a9cdde
color4 #c6c4e9
color5 #86d2f1
color6 #a9cdde
color7 #dfe4e8
color8 #889399
color9 #ffaa97
color10 #86d2f1
color11 #a9cdde
color12 #c6c4e9
color13 #86d2f1
color14 #a9cdde
color15 #dfe4e8

cursor                #dfe4e8
cursor_text_color     #0e1416
background            #0e1416
foreground            #dfe4e8
selection_foreground  #becad0
selection_background  #3e494e
url_color             #86d2f1
