color0 #131314
color1 #ffb4ab
color2 #bec8d0
color3 #c4c7ca
color4 #cfc3d1
color5 #bec8d0
color6 #c4c7ca
color7 #e4e2e2
color8 #8e9194
color9 #ffb4ab
color10 #bec8d0
color11 #c4c7ca
color12 #cfc3d1
color13 #bec8d0
color14 #c4c7ca
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #131314
background            #131314
foreground            #e4e2e2
selection_foreground  #c4c7ca
selection_background  #43474a
active_border_color   #bec8d0
inactive_border_color #43474a
url_color             #bec8d0

active_tab_foreground   #283238
active_tab_background   #bec8d0
inactive_tab_foreground #c4c7ca
inactive_tab_background #43474a
cursor_trail_color      #c4c7ca
