color0 #101413
color1 #ffb4ab
color2 #52dbcb
color3 #b1ccc7
color4 #adcae6
color5 #52dbcb
color6 #b1ccc7
color7 #e0e3e1
color8 #899390
color9 #ffb4ab
color10 #52dbcb
color11 #b1ccc7
color12 #adcae6
color13 #52dbcb
color14 #b1ccc7
color15 #e0e3e1

cursor                #e0e3e1
cursor_text_color     #101413
background            #101413
foreground            #e0e3e1
selection_foreground  #bec9c6
selection_background  #3f4947
active_border_color   #52dbcb
inactive_border_color #3f4947
url_color             #52dbcb
