# : Manager [[[

[mgr]
cwd = { fg = "#dfe4e8" }

# Find
find_keyword = { fg = "#ffaa97", bold = true, italic = true, underline = true }
find_position = { fg = "#ffaa97", bold = true, italic = true }

# Marker
marker_copied = { fg = "#454563", bg = "#454563" }
marker_cut = { fg = "#454563", bg = "#454563" }
marker_marked = { fg = "#ffaa97", bg = "#ffaa97" }
marker_selected = { fg = "#c6c4e9", bg = "#c6c4e9" }

# Count
count_copied = { fg = "#e2e0ff", bg = "#454563" }
count_cut = { fg = "#e2e0ff", bg = "#454563" }
count_selected = { fg = "#00354e", bg = "#c6c4e9" }

# Border
border_style  = { fg = "#86d2f1" }

# : ]]]


# : Status [[[

[status]
overall = { fg = "#86d2f1" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#86d2f1", bg = "#0e1416" }
progress_error = { fg = "#ffaa97", bg = "#0e1416" }

# Permissions
perm_type = { fg = "#a9cdde" }
perm_write = { fg = "#c6c4e9" }
perm_exec = { fg = "#ffaa97" }
perm_read = { fg = "#454563" }
perm_sep = { fg = "#004d67" }

# : ]]]


# : Mode [[[

[mode]

normal_main = { bg = "#86d2f1", fg = "#00354e", bold = true }
normal_alt  = { bg = "#3e494e", fg = "#becad0" }

select_main = { bg = "#a9cdde", fg = "#0e3542", bold = true }
select_alt  = { bg = "#3e494e", fg = "#becad0" }

unset_main = { bg = "#c6c4e9", fg = "#2e2e4b", bold = true }
unset_alt  = { bg = "#3e494e", fg = "#becad0" }

# : ]]]


# : Input [[[

[input]
border = { fg = "#86d2f1" }
title = {}
value = { fg = "#dfe4e8" }
selected = { reversed = true }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#86d2f1", bold = true, bg = "#0e1416" }
inactive = { fg = "#a9cdde", bg = "#0e1416" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#86d2f1", bg = "#00354e" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#86d2f1" }
title = {}
hovered = { fg = "#454563", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#0e1416" }
cand = { fg = "#86d2f1" }
rest = { fg = "#00354e" }
desc = { fg = "#dfe4e8" }
separator = " ▶ "
separator_style = { fg = "#dfe4e8" }

# : ]]]

# : Spotter [[[

[spot]
border   = { fg = "#86d2f1" }
title    = { fg = "#86d2f1" }
tbl_col  = { fg = "#dfe4e8" }
tbl_cell = { fg = "#dfe4e8", bg = "#0e1416" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dfe4e8" }
run = { fg = "#dfe4e8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#0e3542", bg = "#a9cdde" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c6c4e9" }
title_warn = { fg = "#86d2f1" }
title_error = { fg = "#ffaa97" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { mime = "*", is = "orphan", fg = "#ffd5c6", bg = "#950004" },
    { mime = "application/*exec*", fg = "#ffaa97" },

    # Fallback
    { url = "*", fg = "#dfe4e8" },
    { url = "*/", fg = "#86d2f1" },
]

# : ]]]
