#################
### AUTOSTART ###
#################

# exec-once = systemctl --user start hyprpolkitagent // I use noctalia's polkit extension now
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
exec-once = qs -c noctalia-shell
