#####################
### LOOK AND FEEL ###
#####################
$gapsout = 8

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 2
    gaps_out = $gapsout

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $primary
    col.inactive_border = $surface

}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
      enabled = false
        font_size = 16
        font_weight_active = bold
        font_weight_inactive = bold
        col.active = $primary
        col.inactive = $surface
        col.locked_active = $primary
        col.locked_inactive = $surface
        text_color = $surface
        text_color_inactive = $primary
        round_only_edges = true
        render_titles = false
        font_weight_active = bold
        height = 14
        rounding = 4
        indicator_height = 8
        indicator_gap = 0
        gaps_in = 2
        gaps_out = 4
        keep_upper_gap = true
      }
}

decoration {
    rounding = 24
    rounding_power = 6
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    shadow {
      enabled = true
      range = 12
      render_power = 3
      color = rgba(0000006a)
    }

    blur {
        enabled = true
        size = 8
        passes = 3
        brightness = 0.4
        contrast = 0.8
        noise = 0.05
        new_optimizations = on
        ignore_opacity = true
        xray = true
    }
}

# huge gap when there is only window in workspace
# workspace = w[tv1]s[false], gapsout:12, gapsin:0
# workspace = f[1]s[false], gapsout:$gapsout, gapsin:0
