################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-2,1920x1080@165,0x0,1,vrr,1
monitor=IPAD,1180x820@60,360x1080,1
# monitor=IPAD,1770x1230@60,360x1080,1.5
