# regular autostarts
exec-once = [workspace 1 silent] $browser
# exec-once = [workspace 10 silent] org.localsend.localsend_app
exec-once = easyeffects --gapplication-service
exec-once = qs -c overview
bind = $mainMod, A, exec, qs ipc -c overview call overview toggle

exec-once = hyprctl setcursor "macOS" 24

env = HYPRCURSOR_THEME=macOS
env = XCURSOR_THEME=macOS
env = HYPRCURSOR_SIZE=24
env = XCURSOR_SIZE=24

exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'macOS'

input {
    kb_layout = us,tr
    kb_options = caps:escape,grp:win_space_toggle
    accel_profile = flat
    repeat_delay = 250
    follow_mouse = 1
    sensitivity = 0.2 # -1.0 - 1.0, 0 means no modification. }
}

animations {
    enabled = true
}

decoration {
    shadow {
      enabled = true
    }
    blur {
      enabled = true
    }
}

render:direct_scanout=1

