# regular autostarts
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 1 silent] org.localsend.localsend_app
# exec-once = easyeffects --gapplication-service

exec-once = [workspace special:term silent; fullscreen] foot
exec-once = hyprctl setcursor "Bibata-Modern-Classic" 24

input {
    kb_layout = us,tr
    kb_options = caps:escape,grp:win_space_toggle
    accel_profile = flat
    repeat_delay = 250
    follow_mouse = 1
    sensitivity = 0.2 # -1.0 - 1.0, 0 means no modification.
}

animations {
    enabled = true
}

decoration {
    shadow {
      enabled = false
    }
    blur {
      enabled = true
    }
}

render:direct_scanout=1
